# Default values for de-deploy-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
scope: set_by_release_pipeline

image:
  repository: set_by_release_pipeline
  tag: set_by_release_pipeline

service:
  port: 80

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

ingress:
  enabled: true
  hosts:
    - "#{INGRESS_HOST_TOOLS}#"
  path: /deploy-web

resources:
  requests:
    cpu: 100m
    memory: 128Mi
